### ISSUE TITLE
do you have plan release code?

### ISSUE THREAD

**Issue by PyNancy** [ldkong1205/LaserMix#1] opened 2022-09-14 03:20 UTC

**Comment by ldkong1205** [comment] 2022-09-14 03:33
Hi @PyNancy, thank you for your interest in this work! Yes, we plan to release the code in the coming weeks. Please stay tuned!

**Comment by PyNancy** [comment] 2022-09-14 04:58
@ldkong1205  thanks for your reply, i am looking forward your nice work.

**Comment by faikit** [comment] 2022-10-11 09:48
Hi, also looking forward for your code release, about how long it will takes?

**Comment by ldkong1205** [comment] 2022-10-29 02:45
> Hi, also looking forward for your code release, about how long it will takes?

Hi @faikit, thank you for your interest, and sorry for the late reply! We are a bit busy lately. This codebase is planned to have an update next month. The major components, such as the support of different datasets and backbones, will be added in around early December. We will let you know once things are ready. Thanks!

**Comment by vijayM12** [comment] 2022-12-02 14:52
Hello @ldkong1205 I have gone through your work and is really interesting. I have seen your interest in Point cloud translation of SynLiDAR to semanticKitti in the paper "Transfer learning from synthetic to real LiDAR point cloud for semantic segmentation" . I am also doing research on the same topic. Please let me know if you have got any source code for PCT. That would be really helpful if you can share your view on the same

**Comment by ldkong1205** [comment] 2022-12-03 02:19
> Hello @ldkong1205 I have gone through your work and is really interesting. I have seen your interest in Point cloud translation of SynLiDAR to semanticKitti in the paper "Transfer learning from synthetic to real LiDAR point cloud for semantic segmentation" . I am also doing research on the same topic. Please let me know if you have got any resources for implementation code for PCT. That would be really helpful if you can share your view on the same

Hi @vijayM12, thank you for your interest in our work!

As you said, we intended to test the sim2real setting with LaserMix. However, the source code for PCT in the mentioned paper has not been released yet and we actually do not have the plan to re-implement their idea. We are seeking alternatives for achieving this now and we will let you know once we figure it out. Thanks!

**Comment by vijayM12** [comment] 2022-12-03 04:26
> > Hello @ldkong1205 I have gone through your work and is really interesting. I have seen your interest in Point cloud translation of SynLiDAR to semanticKitti in the paper "Transfer learning from synthetic to real LiDAR point cloud for semantic segmentation" . I am also doing research on the same topic. Please let me know if you have got any resources for implementation code for PCT. That would be really helpful if you can share your view on the same
> 
> Hi @vijayM12, thank you for your interest in our work!
> 
> As you said, we intended to test the sim2real setting with LaserMix. However, the source code for PCT in the mentioned paper has not been released yet and we actually do not have the plan to re-implement their idea. We are seeking alternatives for achieving this now and we will let you know once we figure it out. Thanks!

Hello @ldkong1205 Could you please release the source code for LaserMix as soon as possible. It would help me understand better to implement sim2Real

**Comment by ldkong1205** [comment] 2022-12-03 04:37
> > > Hello @ldkong1205 I have gone through your work and is really interesting. I have seen your interest in Point cloud translation of SynLiDAR to semanticKitti in the paper "Transfer learning from synthetic to real LiDAR point cloud for semantic segmentation" . I am also doing research on the same topic. Please let me know if you have got any resources for implementation code for PCT. That would be really helpful if you can share your view on the same
> > 
> > 
> > Hi @vijayM12, thank you for your interest in our work!
> > As you said, we intended to test the sim2real setting with LaserMix. However, the source code for PCT in the mentioned paper has not been released yet and we actually do not have the plan to re-implement their idea. We are seeking alternatives for achieving this now and we will let you know once we figure it out. Thanks!
> 
> Hello @ldkong1205 Could you please release the source code for LaserMix as soon as possible. It would help me understand better to implement sim2Real

Hi @vijayM12, sure! As promised in the previous reply, the code and checkpoints for reproducing our results will be available soon. We are now retouching the codebase and collecting the logs and checkpoints. Please stay tuned~

**Comment by vijayM12** [comment] 2022-12-03 05:25
> > > > Hello @ldkong1205 I have gone through your work and is really interesting. I have seen your interest in Point cloud translation of SynLiDAR to semanticKitti in the paper "Transfer learning from synthetic to real LiDAR point cloud for semantic segmentation" . I am also doing research on the same topic. Please let me know if you have got any resources for implementation code for PCT. That would be really helpful if you can share your view on the same
> > > 
> > > 
> > > Hi @vijayM12, thank you for your interest in our work!
> > > As you said, we intended to test the sim2real setting with LaserMix. However, the source code for PCT in the mentioned paper has not been released yet and we actually do not have the plan to re-implement their idea. We are seeking alternatives for achieving this now and we will let you know once we figure it out. Thanks!
> > 
> > 
> > Hello @ldkong1205 Could you please release the source code for LaserMix as soon as possible. It would help me understand better to implement sim2Real
> 
> Hi @vijayM12, sure! As promised in the previous reply, the code and checkpoints for reproducing our results will be available soon. We are now retouching the codebase and collecting the logs and checkpoints. Please stay tuned~

Ok Thank you

**Comment by vijayM12** [comment] 2022-12-03 06:38
Ok thanks

Regards,
Vijaya Phanindra Kumar M

**Comment by MM-2021** [comment] 2023-03-09 08:43
Hello @ldkong1205，congratulation to you for the LaserMix is accepted to CVPR2023.
Could you release the source code for LaserMix? It will help us to understand LaserMix and follow this great work.

**Comment by ldkong1205** [comment] 2023-03-10 11:52
> Hello @ldkong1205，congratulation to you for the LaserMix is accepted to CVPR2023. Could you release the source code for LaserMix? It will help us to understand LaserMix and follow this great work.

Hi @MM-2021, thanks for your interest in LaserMix!

We have released most of the basic code in this repository. For the semi-supervised training part, we will release the code no later than the camera-ready DDL. For the implementation of laser mixing, here are two resources that you could have a look at first:
- [MMDetection3D](https://github.com/open-mmlab/mmdetection3d) codebase, in which we have included the laser mixing operation as a data augmentation for LiDAR segmentation. Please refer to [this](https://github.com/open-mmlab/mmdetection3d/pull/2302) page for more details.
- [PCSeg](https://github.com/PJLab-ADG/PCSeg) codebase, in which we have tested a simple version (four inclination mixing strategies only) in LaserMix as an augmentation technique for a wide range of LiDAR segmentation methods, and achieved appealing results. Please refer to [this](https://github.com/PJLab-ADG/PCSeg/blob/master/pcseg/data/dataset/semantickitti/LaserMix_semantickitti.py) page for more details.

We will let you know once the remaining parts are completed. Please stay tuned and thanks again for your interest in our work!

**Comment by ldkong1205** [comment] 2023-08-01 13:21
Hi @zhairf, thanks for your interest in this work!

As mentioned here (https://github.com/ldkong1205/LaserMix/issues/6), an enhanced version is coming on the way. We are running experiments now, benchmarking different backbones under different semi-supervised settings (random, sequential, etc.). The new code and checkpoints will be made publicly available.

**Comment by ldkong1205** [comment] 2023-08-29 02:06
We are closing this issue now. Feel free to open a new one if you encounter any problems.

**Closed by ldkong1205** 2023-08-29 02:06 UTC
